///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopCamdex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DesktopCamdexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b8335547-df7c-414d-888e-79eafff2aadd")]
    public partial class DesktopCamdexRepository : RepoGenBaseFolder
    {
        static DesktopCamdexRepository instance = new DesktopCamdexRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DesktopCamdexRepository element repository.
        /// </summary>
        [RepositoryFolder("b8335547-df7c-414d-888e-79eafff2aadd")]
        public static DesktopCamdexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DesktopCamdexRepository() 
            : base("DesktopCamdexRepository", "/", null, 0, false, "b8335547-df7c-414d-888e-79eafff2aadd", ".\\RepositoryImages\\DesktopCamdexRepositoryb8335547.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b8335547-df7c-414d-888e-79eafff2aadd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DesktopCamdexRepositoryFolders
    {
    }
#pragma warning restore 0436
}
